#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 27 16:27:03 GET 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Better MC - Low
enableShaders=false
