#Hard disable entire modules. Use at your own risk and don't ask for support if you use this
#Thu Nov 28 17:30:24 AWST 2024
farmersdelight=true
villagersplus=true
decorative_blocks=true
twigs=true
another_furniture=true
friendsandfoes=true
