#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Mar 26 13:10:56 CDT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Better MC - Low
enableShaders=false
